apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-example-svc-debug
spec:
  ports:
    - port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: admission-webhook-example-svc-debug
subsets:
  - addresses:
      - ip: ${K8S_MASTER_IP} # 需要替换成K8S集群Master节点的IP
    ports:
      - port: 444